export interface Student {
  name: string;
  score: number;
}

export const students: Student[] = [
  { name: "AYED Malek", score: 16.76 },
  { name: "BELHAJ HSSINE Mohamed Aziz", score: 15.35 },
  { name: "BEN ACHOUR Malek", score: 13.1 },
  { name: "BEN JEDDOU Yassine", score: 16.8 },
  { name: "BEN OTHMEN Ons", score: 13.16 },
  { name: "BEN SAID Adem", score: 14.75 },
  { name: "BENARIBIA Aroussi", score: 14.48 },
  { name: "BICHIOU Amine", score: 15.41 },
  { name: "CHERNI Samar", score: 14.62 },
  { name: "CHOUK Achraf", score: 4.83 },
  { name: "DHIB Ahmed", score: 14.81 },
  { name: "EL KAMEL Nada", score: 15.87 },
  { name: "EL OUNI Ilyes", score: 16.47 },
  { name: "FTITI Firas", score: 14.8 },
  { name: "GAOUET Ayoub", score: 15.93 },
  { name: "HAFSIA Achraf", score: 15.84 },
  { name: "HAJOUNI Zakia", score: 16.02 },
  { name: "HAMMAMI Youssef", score: 14.3 },
  { name: "HAOUAS Nada", score: 14.62 },
  { name: "HATTAB Fatma", score: 15.08 },
  { name: "KEFI Badis", score: 15.58 },
  { name: "LAMOUCHI Taha Yassine", score: 15.75 },
  { name: "LAOUINI Eya", score: 11.92 },
  { name: "LTAIEF Khalil", score: 16.11 },
  { name: "MANSOUR Maher", score: 15.5 },
  { name: "MAYARA Ahmed", score: 16.11 },
  { name: "MISSAOUI Skander", score: 10.66 },
  { name: "MONTACER Mohamed Yassine", score: 12.92 },
  { name: "OTHMANI Rayen", score: 15.05 },
  { name: "RAIES Asma", score: 14.59 },
  { name: "RAZZEG DIT GUIRAS Chaima", score: 16.2 },
  { name: "ABAIDI Walid", score: 7.68 },
  { name: "ABBASSI Touwa", score: 13.22 },
  { name: "ABDELKHALEK Abdelkader", score: 8.78 },
  { name: "ARFA Azer", score: 14 },
  { name: "AYARI Ayoub", score: 14.33 },
  { name: "BARHOUMI Raja", score: 16.56 },
  { name: "BAYOUDH Rawel", score: 11.15 },
  { name: "BEN ATTIA Khaoula", score: 7.17 },
  { name: "BEN YOUNES Iheb", score: 13.61 },
  { name: "BENOTHMEN Aroussi", score: 5.95 },
  { name: "BOUAOUINA Ali", score: 9.62 },
  { name: "CHARAI Sarra", score: 11.65 },
  { name: "CHMAINGUI Abir", score: 11.04 },
  { name: "DAAS Houssem", score: 13.41 },
  { name: "DGHAIS Zeineb", score: 12.28 },
  { name: "GUESMI Iram", score: 12.36 },
  { name: "HAMDI Amal", score: 15.24 },
  { name: "HAMI Islem", score: 11.16 },
  { name: "HAMMAMI Houssem", score: 15.96 },
  { name: "KHACHECHE Imen", score: 15.97 },
  { name: "MAJDOUB Mohamed Amine", score: 13.2 },
  { name: "MBARKI Chaima", score: 14.28 },
  { name: "MGHIRBI Sadok Aziz", score: 13.42 },
  { name: "NOUISSER Amine", score: 15.06 },
  { name: "OUALI Louay", score: 12.74 },
  { name: "RABHI Riadh", score: 10.48 },
  { name: "RAGMOUN Raoua", score: 13.12 },
  { name: "REBAI Chedly", score: 13.91 },
  { name: "RIAHI Jihene", score: 6.6 },
  { name: "SAAD Omar", score: 13.56 },
  { name: "SAYADI Salim", score: 11.18 },
  { name: "SELLAMI Asma", score: 14.64 },
  { name: "ZOUAOU I Rihab", score: 13.81 },
  { name: "ABDESSATAR Chirine", score: 11.87 },
  { name: "AMARA Hanin", score: 16.42 },
  { name: "BELLALOUNA Ghalia", score: 15.51 },
  { name: "BEN ATTIA Souad", score: 15.45 },
  { name: "BEN RHOUMA Souleima", score: 13.67 },
  { name: "BENMRAD Bilel", score: 16.66 },
  { name: "BOUAFIF Mohamed Habib", score: 10.38 },
  { name: "BOURGUIBA Mohamed", score: 13.03 },
  { name: "CHAOUATI Khaoula", score: 14.7 },
  { name: "CHOUK Ons", score: 13.33 },
  { name: "DACHRAOUI Emna", score: 10.64 },
  { name: "DAKHLAOUI BENHAJAL Mariem", score: 15.42 },
  { name: "DJEBBI Haythem", score: 13.93 },
  { name: "ELBACH Hamza", score: 12.58 },
  { name: "ELGARSSI Tesnime", score: 15.59 },
  { name: "FKI Farah", score: 12.7 },
  { name: "FROUJA Asma", score: 6.62 },
  { name: "GARA ALI Nour", score: 13.25 },
  { name: "GUIRATI Nour", score: 15.16 },
  { name: "HBACHA Dorra", score: 4.82 },
  { name: "KETHIRI Mohamed Youssef", score: 13.77 },
  { name: "LOUSSAIEF Dalel", score: 14.88 },
  { name: "MAHDI Laith", score: 14.82 },
  { name: "OUERFELI Meissa", score: 13.36 },
  { name: "RAZEK Habib", score: 15.81 },
  { name: "RCHIDI Koussay", score: 14.5 },
  { name: "TAGHOUTI Siwar", score: 13.93 },
  { name: "TAHER Rahma", score: 7.82 },
  { name: "TROUDI Rayen", score: 15.58 },
  { name: "YAZIDI Ons", score: 12.28 },
  { name: "HALI Eya", score: 12.3 },
  { name: "HALI Safwen", score: 13.02 },
  { name: "MANERI Othmene", score: 14.44 },
  { name: "MANSOUR Ahmed", score: 13.06 },
  { name: "SHILI Ebtihel", score: 12.54 },
];
