export interface Student {
  name: string;
  score: number;
}

export const students_3eme: Student[] = [
  { name: "AYED Malek", score: 16.76 },
  { name: "BELHAJ HSSINE Mohamed Aziz", score: 15.35 },
  { name: "BEN ACHOUR Malek", score: 13.1 },
  { name: "BEN JEDDOU Yassine", score: 16.8 },
  { name: "BEN OTHMEN Ons", score: 13.16 },
  { name: "BEN SAID Adem", score: 14.75 },
  { name: "BENARIBIA Aroussi", score: 14.48 },
  { name: "BICHIOU Amine", score: 15.41 },
  { name: "CHERNI Samar", score: 14.62 },
  { name: "CHOUK Achraf", score: 4.83 },
  { name: "DHIB Ahmed", score: 14.81 },
  { name: "EL KAMEL Nada", score: 15.87 },
  { name: "EL OUNI Ilyes", score: 16.47 },
  { name: "FTITI Firas", score: 14.8 },
  { name: "GAOUET Ayoub", score: 15.93 },
  { name: "HAFSIA Achraf", score: 15.84 },
  { name: "HAJOUNI Zakia", score: 16.02 },
  { name: "HAMMAMI Youssef", score: 14.3 },
  { name: "HAOUAS Nada", score: 14.62 },
  { name: "HATTAB Fatma", score: 15.08 },
  { name: "KEFI Badis", score: 15.58 },
  { name: "LAMOUCHI Taha Yassine", score: 15.75 },
  { name: "LAOUINI Eya", score: 11.92 },
  { name: "LTAIEF Khalil", score: 16.11 },
  { name: "MANSOUR Maher", score: 15.5 },
  { name: "MAYARA Ahmed", score: 16.11 },
  { name: "MISSAOUI Skander", score: 10.66 },
  { name: "MONTACER Mohamed Yassine", score: 12.92 },
  { name: "OTHMANI Rayen", score: 15.05 },
  { name: "RAIES Asma", score: 14.59 },
  { name: "RAZZEG DIT GUIRAS Chaima", score: 16.2 },
  { name: "ABAIDI Walid", score: 7.68 },
  { name: "ABBASSI Touwa", score: 13.22 },
  { name: "ABDELKHALEK Abdelkader", score: 8.78 },
  { name: "ARFA Azer", score: 14 },
  { name: "AYARI Ayoub", score: 14.33 },
  { name: "BARHOUMI Raja", score: 16.56 },
  { name: "BAYOUDH Rawel", score: 11.15 },
  { name: "BEN ATTIA Khaoula", score: 7.17 },
  { name: "BEN YOUNES Iheb", score: 13.61 },
  { name: "BENOTHMEN Aroussi", score: 5.95 },
  { name: "BOUAOUINA Ali", score: 9.62 },
  { name: "CHARAI Sarra", score: 11.65 },
  { name: "CHMAINGUI Abir", score: 11.04 },
  { name: "DAAS Houssem", score: 13.41 },
  { name: "DGHAIS Zeineb", score: 12.28 },
  { name: "GUESMI Iram", score: 12.36 },
  { name: "HAMDI Amal", score: 15.24 },
  { name: "HAMI Islem", score: 11.16 },
  { name: "HAMMAMI Houssem", score: 15.96 },
  { name: "KHACHECHE Imen", score: 15.97 },
  { name: "MAJDOUB Mohamed Amine", score: 13.2 },
  { name: "MBARKI Chaima", score: 14.28 },
  { name: "MGHIRBI Sadok Aziz", score: 13.42 },
  { name: "NOUISSER Amine", score: 15.06 },
  { name: "OUALI Louay", score: 12.74 },
  { name: "RABHI Riadh", score: 10.48 },
  { name: "RAGMOUN Raoua", score: 13.12 },
  { name: "REBAI Chedly", score: 13.91 },
  { name: "RIAHI Jihene", score: 6.6 },
  { name: "SAAD Omar", score: 13.56 },
  { name: "SAYADI Salim", score: 11.18 },
  { name: "SELLAMI Asma", score: 14.64 },
  { name: "ZOUAOU I Rihab", score: 13.81 },
  { name: "ABDESSATAR Chirine", score: 11.87 },
  { name: "AMARA Hanin", score: 16.42 },
  { name: "BELLALOUNA Ghalia", score: 15.51 },
  { name: "BEN ATTIA Souad", score: 15.45 },
  { name: "BEN RHOUMA Souleima", score: 13.67 },
  { name: "BENMRAD Bilel", score: 16.66 },
  { name: "BOUAFIF Mohamed Habib", score: 10.38 },
  { name: "BOURGUIBA Mohamed", score: 13.03 },
  { name: "CHAOUATI Khaoula", score: 14.7 },
  { name: "CHOUK Ons", score: 13.33 },
  { name: "DACHRAOUI Emna", score: 10.64 },
  { name: "DAKHLAOUI BENHAJAL Mariem", score: 15.42 },
  { name: "DJEBBI Haythem", score: 13.93 },
  { name: "ELBACH Hamza", score: 12.58 },
  { name: "ELGARSSI Tesnime", score: 15.59 },
  { name: "FKI Farah", score: 12.7 },
  { name: "FROUJA Asma", score: 6.62 },
  { name: "GARA ALI Nour", score: 13.25 },
  { name: "GUIRATI Nour", score: 15.16 },
  { name: "HBACHA Dorra", score: 4.82 },
  { name: "KETHIRI Mohamed Youssef", score: 13.77 },
  { name: "LOUSSAIEF Dalel", score: 14.88 },
  { name: "MAHDI Laith", score: 14.82 },
  { name: "OUERFELI Meissa", score: 13.36 },
  { name: "RAZEK Habib", score: 15.81 },
  { name: "RCHIDI Koussay", score: 14.5 },
  { name: "TAGHOUTI Siwar", score: 13.93 },
  { name: "TAHER Rahma", score: 7.82 },
  { name: "TROUDI Rayen", score: 15.58 },
  { name: "YAZIDI Ons", score: 12.28 },
  { name: "HALI Eya", score: 12.3 },
  { name: "HALI Safwen", score: 13.02 },
  { name: "MANERI Othmene", score: 14.44 },
  { name: "MANSOUR Ahmed", score: 13.06 },
  { name: "SHILI Ebtihel", score: 12.54 },
];

export const students_2eme: Student[] = [
  { name: "ABAIDI Walid", score: 11.02 },
  { name: "ABIDI Ala", score: 9.72 },
  { name: "ARFA Azer", score: 12.56 },
  { name: "AYARI Ayoub", score: 12.1 },
  { name: "BARHOUMI Raja", score: 16.09 },
  { name: "BAYOUDI Rawel", score: 11.06 },
  { name: "BEN ATTIA Khaoula", score: 11.1 },
  { name: "BEN HARIZ Firas", score: 12.85 },
  { name: "BEN KHALIFA Youssef", score: 1.78 },
  { name: "BEN SALAH Nassim", score: 12.46 },
  { name: "BEN YOUNES Iheb", score: 11.67 },
  { name: "BENOTHMEN Arsouini", score: 11.88 },
  { name: "CHARAI Sarra", score: 11.26 },
  { name: "Chmainguai Abir", score: 10.52 },
  { name: "DAAS Houssem", score: 10.1 },
  { name: "DGHAIS Zeineb", score: 11.66 },
  { name: "EIABESSI Touwa", score: 12.66 },
  { name: "GUESMI Iram", score: 11.68 },
  { name: "HAJJI Khalil", score: 11.41 },
  { name: "HAMDI Amal", score: 14.75 },
  { name: "HAMI Islem", score: 10.82 },
  { name: "HAMMAMI Houssem", score: 12.66 },
  { name: "KHACHECHE Imen", score: 14.22 },
  { name: "MAJDOUB Mohamed Amine", score: 11.56 },
  { name: "MBARKI Chaima", score: 12.41 },
  { name: "MGHIRBI Sadok Aziz", score: 12.28 },
  { name: "MHAMED Oussema", score: 5.94 },
  { name: "NAAS Mohamed Aziz", score: 1.14 },
  { name: "NOUSSER Amine", score: 12.6 },
  { name: "OUALI Louay", score: 10.3 },
  { name: "RAGMOUN Raoua", score: 10.78 },
  { name: "REBAI Chedly", score: 12.36 },
  { name: "RIAHI Hadil", score: 9.76 },
  { name: "RIAHI Jhene", score: 10.88 },
  { name: "SAAD Omar", score: 11.52 },
  { name: "SAYADI Salim", score: 10.16 },
  { name: "SELLAMI Asma", score: 13 },
  { name: "ZOUAOUI Rihab", score: 13.01 },
  { name: "ABDESSATAR Chirine", score: 11.7 },
  { name: "AMARA Hanin", score: 15.36 },
  { name: "BELLAOUNA Ghalia", score: 13.66 },
  { name: "BEN ATTIA Souad", score: 13.86 },
  { name: "BEN MAJDOUBA Balkis", score: 9.68 },
  { name: "BEN RHOUMA Souleima", score: 10.96 },
  { name: "BENMRAD Bilel", score: 14.63 },
  { name: "BOURGUIBA Mohamed", score: 11.76 },
  { name: "CHAOUIATI Khaoula", score: 13.48 },
  { name: "CHERNI Samar", score: 14.56 },
  { name: "CHOUK Ons", score: 10.3 },
  { name: "DACHRAOUI Emna", score: 12.38 },
  { name: "DAKHLOU BENHAJAL Mariem", score: 14.92 },
  { name: "DJEBBI Haythem", score: 12.45 },
  { name: "ELBACH Hamza", score: 11.34 },
  { name: "ELGARSSI Tesnime", score: 14.96 },
  { name: "FKI Farah", score: 10.52 },
  { name: "FROUJA Asma", score: 11.66 },
  { name: "GARA ALI Nour", score: 10.94 },
  { name: "GUIRATI Nour", score: 13.33 },
  { name: "HBACHA Dorra", score: 10.75 },
  { name: "KETHIRI Mohamed Youssef", score: 12.93 },
  { name: "LOUSSAIEF Dalel", score: 11.23 },
  { name: "MAHDI Laith", score: 11.41 },
  { name: "OUERFELI Meissa", score: 12.8 },
  { name: "RCHIDI Koussay", score: 13.48 },
  { name: "SAADAOUI Louay", score: 9.41 },
  { name: "SAFFAR Bilel", score: 10.92 },
  { name: "TAGHOUTI Siwar", score: 11.48 },
  { name: "TAHER Rahma", score: 11.19 },
  { name: "TROUDI Rayen", score: 12.8 },
  { name: "YAZIDI Ons", score: 11.09 },
  { name: "AYED Malek", score: 15.95 },
  { name: "BACCOUCH Gaith", score: 8.82 },
  { name: "BELHAJ HASSINE Mohamed Aziz", score: 12.86 },
  { name: "BEN ACHOUR Malek", score: 11.8 },
  { name: "BEN JEDDOU Yassine", score: 16.32 },
  { name: "BEN OTHMEN Ons", score: 11.65 },
  { name: "BEN SAID Adem", score: 12.07 },
  { name: "BEN SLAMA Adem", score: 9.94 },
  { name: "BENARIBIA Aroussi", score: 12 },
  { name: "BICHIOU Amine", score: 13.48 },
  { name: "DGHAIES Akram", score: 8.7 },
  { name: "DHIB Ahmed", score: 12.76 },
  { name: "EL KAMEL Nada", score: 14.36 },
  { name: "EL OUNI Ilyes", score: 14.92 },
  { name: "FTITI Firas", score: 11.73 },
  { name: "GAOUET Ayoub", score: 11.9 },
  { name: "HAFSIA Achraf", score: 12.88 },
  { name: "HAJOUNI Zakia", score: 13.75 },
  { name: "HAMMAMI Youssef", score: 11.08 },
  { name: "HAOUAS Nada", score: 14.24 },
  { name: "HATTAB Fatma", score: 12.86 },
  { name: "JABRI Rayen", score: 3.85 },
  { name: "KEFI Badis", score: 12.58 },
  { name: "LAMOUCHI Taha Yassine", score: 15 },
  { name: "LAOUNI Eya", score: 11.94 },
  { name: "LOUHICHI Oussema", score: 9.16 },
  { name: "LTAIEF Khalil", score: 13.88 },
  { name: "MAAROUFI Ghizlen", score: 9.8 },
  { name: "MANSOUR Maher", score: 13.62 },
  { name: "MAYARA Ahmed", score: 14.67 },
  { name: "OTHMANI Rayen", score: 11.49 },
  { name: "RAIES Asma", score: 13.36 },
  { name: "RAZEK Habib", score: 13.28 },
  { name: "RAZZEG DIT GUIRAS Chaima", score: 14.09 },
  { name: "SOUISSI Ahmed", score: 12.37 },
];
